Update run-trivy.yml

diff --git a/.github/workflows/run-trivy.yml b/.github/workflows/run-trivy.yml
--- a/.github/workflows/run-trivy.yml
+++ b/.github/workflows/run-trivy.yml
@@ -7,18 +7,19 @@ on:
     branches: [ main ]
 
 jobs:
-
-- name: Manifest Generation
-  run: |
-    curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
-    curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
-    if ! cat install.sh.checksum | shasum -a 256 ; then
-      echo "install.sh checksum failed"
-      exit 1
-    fi
-    sh install.sh
-    rm install.sh install.sh.checksum
-    billy generate \
+  trivy:
+  - 
+    name: Manifest Generation
+    run: |
+      curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
+      curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
+      if ! cat install.sh.checksum | shasum -a 256 ; then
+        echo "install.sh checksum failed"
+        exit 1
+      fi
+      sh install.sh
+      rm install.sh install.sh.checksum
+      billy generate \
         --access-token "${{ secrets.GITHUB_TOKEN }}" \
         --aqua-key "${{ secrets.AQUA_KEY }}" \
         --aqua-secret "${{ secrets.AQUA_SECRET }}" \
